/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId.index'
import { Route as ProjectsProjectIdLayoutRouteImport } from './routes/projects/$projectId._layout'
import { Route as ProjectsProjectIdDataRouteImport } from './routes/projects/$projectId/data'
import { Route as ProjectsProjectIdRequirementsRouteImport } from './routes/projects/$projectId/requirements'
import { Route as ProjectsProjectIdStoryMapRouteImport } from './routes/projects/$projectId/story-map'
import { Route as ProjectsProjectIdTasksRouteImport } from './routes/projects/$projectId/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLayoutRoute = ProjectsProjectIdLayoutRouteImport.update({
  id: '/projects/$projectId/_layout',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdDataRoute = ProjectsProjectIdDataRouteImport.update({
  id: '/projects/$projectId/data',
  path: '/projects/$projectId/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRequirementsRoute =
  ProjectsProjectIdRequirementsRouteImport.update({
    id: '/projects/$projectId/requirements',
    path: '/projects/$projectId/requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdStoryMapRoute =
  ProjectsProjectIdStoryMapRouteImport.update({
    id: '/projects/$projectId/story-map',
    path: '/projects/$projectId/story-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdTasksRoute = ProjectsProjectIdTasksRouteImport.update({
  id: '/projects/$projectId/tasks',
  path: '/projects/$projectId/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdLayoutRoute
  '/projects/$projectId/data': typeof ProjectsProjectIdDataRoute
  '/projects/$projectId/requirements': typeof ProjectsProjectIdRequirementsRoute
  '/projects/$projectId/story-map': typeof ProjectsProjectIdStoryMapRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/data': typeof ProjectsProjectIdDataRoute
  '/projects/$projectId/requirements': typeof ProjectsProjectIdRequirementsRoute
  '/projects/$projectId/story-map': typeof ProjectsProjectIdStoryMapRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/_layout': typeof ProjectsProjectIdLayoutRoute
  '/projects/$projectId/data': typeof ProjectsProjectIdDataRoute
  '/projects/$projectId/requirements': typeof ProjectsProjectIdRequirementsRoute
  '/projects/$projectId/story-map': typeof ProjectsProjectIdStoryMapRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/projects/'
    | '/projects/$projectId'
    | '/projects/$projectId/data'
    | '/projects/$projectId/requirements'
    | '/projects/$projectId/story-map'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/data'
    | '/projects/$projectId/requirements'
    | '/projects/$projectId/story-map'
    | '/projects/$projectId/tasks'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/projects/'
    | '/projects/$projectId/_layout'
    | '/projects/$projectId/data'
    | '/projects/$projectId/requirements'
    | '/projects/$projectId/story-map'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdLayoutRoute: typeof ProjectsProjectIdLayoutRoute
  ProjectsProjectIdDataRoute: typeof ProjectsProjectIdDataRoute
  ProjectsProjectIdRequirementsRoute: typeof ProjectsProjectIdRequirementsRoute
  ProjectsProjectIdStoryMapRoute: typeof ProjectsProjectIdStoryMapRoute
  ProjectsProjectIdTasksRoute: typeof ProjectsProjectIdTasksRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/_layout': {
      id: '/projects/$projectId/_layout'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/data': {
      id: '/projects/$projectId/data'
      path: '/projects/$projectId/data'
      fullPath: '/projects/$projectId/data'
      preLoaderRoute: typeof ProjectsProjectIdDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/requirements': {
      id: '/projects/$projectId/requirements'
      path: '/projects/$projectId/requirements'
      fullPath: '/projects/$projectId/requirements'
      preLoaderRoute: typeof ProjectsProjectIdRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/story-map': {
      id: '/projects/$projectId/story-map'
      path: '/projects/$projectId/story-map'
      fullPath: '/projects/$projectId/story-map'
      preLoaderRoute: typeof ProjectsProjectIdStoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tasks': {
      id: '/projects/$projectId/tasks'
      path: '/projects/$projectId/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof ProjectsProjectIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdLayoutRoute: ProjectsProjectIdLayoutRoute,
  ProjectsProjectIdDataRoute: ProjectsProjectIdDataRoute,
  ProjectsProjectIdRequirementsRoute: ProjectsProjectIdRequirementsRoute,
  ProjectsProjectIdStoryMapRoute: ProjectsProjectIdStoryMapRoute,
  ProjectsProjectIdTasksRoute: ProjectsProjectIdTasksRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
